Repository k3d-io/k3d, pull requests merged in 2020-12, with the labels that each got.

#416 [Feature] Options for formatted output of `cluster list` (#416, @inercia))
  cmd/cluster/clusterList.go
  go.mod
  pkg/types/types.go
  vendor/modules.txt
Labels: enhancement

#421 [Fix] Allow literal @ in flags that have nodefilters
  cmd/util/filter.go
  tests/test_basic.sh
Labels: bug

#427 [Refactoring/Preparation] use real port structs as prep for registries
  Makefile
  cmd/cluster/clusterCreate.go
  cmd/registry/registryCreate.go
  cmd/util/ports.go
  pkg/client/cluster.go
  pkg/client/node.go
  pkg/client/registry.go
  pkg/config/config_test.go
  pkg/config/test_assets/config_test_simple.yaml
  pkg/config/transform.go
  pkg/config/v1alpha1/types.go
  pkg/config/validate.go
  pkg/runtimes/docker/translate.go
  pkg/runtimes/docker/translate_test.go
  pkg/types/types.go
  pkg/util/ports.go
  tests/dind.sh
Labels: breaking change, enhancement
