Repository k3d-io/k3d, pull requests merged in 2021-11, with the labels that each got.

#841 feat: fetch K3s image tag from channelserver on latest/stable/+min.major
  cmd/cluster/clusterCreate.go
  cmd/node/nodeCreate.go
  go.mod
  go.sum
  pkg/config/transform.go
  pkg/config/v1alpha2/types.go
  pkg/config/v1alpha3/types.go
  pkg/types/k3s/channel.go
  vendor/github.com/docker/distribution/manifest/schema1/config_builder.go
  vendor/github.com/docker/distribution/manifest/schema1/manifest.go
  vendor/github.com/docker/distribution/manifest/schema1/reference_builder.go
  vendor/github.com/docker/distribution/manifest/schema1/sign.go
  vendor/github.com/docker/distribution/manifest/schema1/verify.go
  vendor/github.com/docker/libtrust/CONTRIBUTING.md
  vendor/github.com/docker/libtrust/LICENSE
  vendor/github.com/docker/libtrust/MAINTAINERS
  vendor/github.com/docker/libtrust/README.md
  vendor/github.com/docker/libtrust/certificates.go
  vendor/github.com/docker/libtrust/doc.go
  vendor/github.com/docker/libtrust/ec_key.go
  vendor/github.com/docker/libtrust/filter.go
  vendor/github.com/docker/libtrust/hash.go
  vendor/github.com/docker/libtrust/jsonsign.go
  vendor/github.com/docker/libtrust/key.go
  vendor/github.com/docker/libtrust/key_files.go
  vendor/github.com/docker/libtrust/key_manager.go
  vendor/github.com/docker/libtrust/rsa_key.go
  vendor/github.com/docker/libtrust/util.go
  vendor/github.com/heroku/docker-registry-client/LICENSE.md
  vendor/github.com/heroku/docker-registry-client/registry/authchallenge.go
  vendor/github.com/heroku/docker-registry-client/registry/basictransport.go
  vendor/github.com/heroku/docker-registry-client/registry/blob.go
  vendor/github.com/heroku/docker-registry-client/registry/errortransport.go
  vendor/github.com/heroku/docker-registry-client/registry/json.go
  vendor/github.com/heroku/docker-registry-client/registry/manifest.go
  vendor/github.com/heroku/docker-registry-client/registry/registry.go
  vendor/github.com/heroku/docker-registry-client/registry/repositories.go
  vendor/github.com/heroku/docker-registry-client/registry/tags.go
  vendor/github.com/heroku/docker-registry-client/registry/tokentransport.go
  vendor/modules.txt
  version/version.go
  version/version_test.go
Labels: enhancement

#845 docs: add documentation on k3s features
  docs/usage/.pages
  docs/usage/k3s.md
Labels: docs

#848 [Enhancement] tests/e2e: speedup & cleanup
  tests/common.sh
  tests/extra_test_k3s_versions.sh
  tests/runner.sh
  tests/test_basic.sh
  tests/test_config_file.sh
  tests/test_config_file_migration.sh
  tests/test_config_with_overrides.sh
  tests/test_full_lifecycle.sh
  tests/test_ipam.sh
  tests/test_loadbalancer.sh
  tests/test_memory_limits.sh
  tests/test_multi_master.sh
  tests/test_multi_master_start_stop.sh
  tests/test_node_edit.sh
  tests/test_registry.sh
Labels: enhancement, priority/medium

#849 [FIX] Fix/e2e-speedup-nofails
  Makefile
  pkg/client/cluster.go
  tests/assets/config_test_simple.yaml
  tests/common.sh
  tests/dind.sh
  tests/extra_test_k3s_versions.sh
  tests/runner.sh
  tests/test_basic.sh
  tests/test_config_file.sh
  tests/test_config_file_migration.sh
  tests/test_config_with_overrides.sh
  tests/test_full_lifecycle.sh
  tests/test_ipam.sh
  tests/test_loadbalancer.sh
  tests/test_memory_limits.sh
  tests/test_multi_master.sh
  tests/test_multi_master_start_stop.sh
  tests/test_node_edit.sh
  tests/test_registry.sh
Labels: bug, priority/high

#860 [FIX] clusterCreate: process simpleConfig before validation step to avoid early exit in hostnetwork mode
  cmd/cluster/clusterCreate.go
  pkg/config/process.go
Labels: priority/high, scope/package

#826 [Enhancement]: improve image loading performance
  cmd/image/imageImport.go
  docs/usage/.pages
  docs/usage/commands/k3d_image_import.md
  docs/usage/importing_images.md
  pkg/client/tools.go
  pkg/runtimes/docker/node.go
  pkg/runtimes/runtime.go
  pkg/types/types.go
Labels: enhancement, priority/medium, scope/package

#871 [Enhancement] extend usability of nodefilters with suffices internally...
  pkg/client/ports.go
  pkg/config/transform.go
  pkg/util/filter.go
Labels: enhancement

#870 [Feature] Add command to list image tags
  cmd/root.go
  go.mod
  go.sum
  pkg/types/k3s/channel.go
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/context.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_other.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/modules.txt
Labels: enhancement, scope/cli
