Repository k3d-io/k3d, pull requests merged in 2021-03, with the labels that each got.

#496 [Enhancement] Add status column to registry list
  cmd/registry/registryList.go
Labels: enhancement

#530 [Enhancement] build: add darwin/arm64 (Silicon, M1) build target
  Makefile
Labels: enhancement

#529 [Enhancement] jsonschema: use Go1.16's go:embed to embed the json schema file (dedup)
  pkg/config/jsonschema_test.go
  pkg/config/v1alpha2/schema.go
  pkg/config/v1alpha2/types.go
Labels: enhancement

#500 [FIX] Properly handle host/hostIP cases for kubeconfig (#500, @fabricev)
  pkg/config/transform.go
Labels: bug

#532 [Enhancement] docs/help: clarify registry names (naming & k3d-prefix)
  cmd/registry/registryCreate.go
  docs/usage/guides/registries.md
Labels: enhancement

#534 [Enhancement] docs: add page about the config file
  docs/usage/.pages
  docs/usage/configfile.md
Labels: docs, enhancement

#494 [FEATURE] Memory Limits (#494, @konradmalik)
  cmd/cluster/clusterCreate.go
  cmd/node/nodeCreate.go
  go.mod
  pkg/client/node.go
  pkg/config/transform.go
  pkg/config/v1alpha2/schema.json
  pkg/config/v1alpha2/types.go
  pkg/config/validate.go
  pkg/runtimes/docker/container.go
  pkg/runtimes/docker/translate.go
  pkg/types/types.go
  pkg/util/infofaker.go
  vendor/modules.txt
Labels: enhancement
