Repository k3d-io/k3d, pull requests merged in 2021-01, with the labels that each got.

#441 [Feature] add LocalRegistryHostingV1 from KEP-1755
  CHANGELOG.md
  pkg/client/cluster.go
  pkg/client/registry.go
  pkg/client/registry_test.go
  pkg/client/test.json
  pkg/types/k8s/registry.go
  tests/test_registry.sh
Labels: enhancement

#442 [Fix] nil-pointer exception when eyposing port on loadbalancer with --no-lb set
  pkg/util/filter.go
Labels: bug

#443 [DOCS] Add Chocolatey install option
  README.md
  docs/index.md
Labels: docs

#439 [Enhancement] Improved listings for nodes & registries (#439, @inercia)
  cmd/node/nodeList.go
  cmd/registry/registryList.go
  cmd/util/listings.go
Labels: enhancement

#453 [Feature] Allow k3d-managed + externally configured registries at the same time
  cmd/cluster/clusterCreate.go
  docs/usage/guides/registries.md
  pkg/client/cluster.go
  pkg/client/registry.go
  pkg/config/transform.go
  pkg/config/v1alpha1/types.go
  pkg/types/types.go
  pkg/util/filter.go
  tests/assets/config_test_simple.yaml
  tests/assets/test_registries.yaml
  tests/common.sh
  tests/test_config_file.sh
  tests/test_full_lifecycle.sh
Labels: enhancement

#454 [Fix] registry: adjustments on how the registry is perceived
  pkg/client/cluster.go
  pkg/client/registry.go
  pkg/client/registry_test.go
  pkg/types/types.go
Labels: bug, enhancement
