Repository k3d-io/k3d, pull requests merged in 2021-08, with the labels that each got.

#693 [FIX] Do not override hostIP when hostPort is missing (#693, @lukaszo)
  cmd/cluster/clusterCreate.go
Labels: bug

#712 [Enhancement] Improved Pipeline for Multiarch Images and SemVer Tags
  .drone.yml
  Dockerfile
  dind-manifest.tmpl
  manifest.tmpl
  proxy/manifest.tmpl
  tools/manifest.tmpl
Labels: enhancement

#701 [FIX]: import all requested images (#701, @mszostok)
  pkg/tools/tools.go
  pkg/tools/tools_test.go
Labels: bug, enhancement

#718 [Enhancement] DNS Injection
  cmd/cluster/clusterCreate.go
  docs/usage/configfile.md
  go.mod
  pkg/client/cluster.go
  pkg/config/process.go
  pkg/config/process_test.go
  pkg/config/transform.go
  pkg/config/v1alpha3/schema.json
  pkg/config/v1alpha3/types.go
  pkg/runtimes/docker/network.go
  pkg/runtimes/docker/translate.go
  pkg/types/types.go
Labels: enhancement, priority/high, breaking change, scope/cli, scope/package, component/main
