Repository k3d-io/k3d, pull requests merged in 2022-02, with the labels that each got.

#952 fix: mutex on ensureToolsNode to avoid duplicate container name causing error
  pkg/client/tools.go
Labels: bug, enhancement

#955 [Fix] detect '--disable=coredns' and conditionally disable injection
  pkg/client/cluster.go
Labels: bug, enhancement, priority/medium, scope/package, component/main

#966 ci/action/arch: Switch from absolute Arch docker version to a more relaxed one
  .github/workflows/aur-prerelease.yml
  .github/workflows/aur-release.yml
  deploy-aur.sh
Labels: enhancement
