Repository k3d-io/k3d, pull requests merged in 2022-03, with the labels that each got.

#986 fix: Use bridge as the default networking mode
  pkg/runtimes/docker/translate.go
Labels: enhancement

#977 [Enhancement] GitHub Actions
  .drone.yml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  docker-bake.hcl
  proxy/Dockerfile
  proxy/install-confd.sh
  scripts/install-tools.sh
Labels: enhancement, priority/high

#1027 [FIX] GetGatewayIP for host.k3d.internal should error out if there's no gateway defined
  pkg/runtimes/docker/network.go
Labels: bug

#1032 add: node create --k3s-arg flag
  cmd/node/nodeCreate.go
Labels: enhancement

#1033 [CHORE] change: update docs requirements and re-run docgen for commands
  docgen/go.mod
  docgen/go.sum
  docs/requirements.txt
  docs/usage/commands/k3d_cluster_create.md
  docs/usage/commands/k3d_completion.md
  docs/usage/commands/k3d_image_import.md
  docs/usage/commands/k3d_node_create.md
  docs/usage/commands/k3d_registry_create.md
Labels: enhancement, docs

#1034 change: no default image for node creation in local cluster where image should be copied from existing nodes
  cmd/node/nodeCreate.go
  pkg/client/node.go
Labels: enhancement

#1035 Release/v5.4.0
  .github/workflows/release.yaml
  CHANGELOG.md
  Makefile
  README.md
  docs/usage/commands/k3d_node_create.md
Labels: enhancement
